### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Ehren38** [dustinfife/fifer#7]
I attempted to install your package like this:
   install.packages("remotes")
   library(remotes)
   install.packages("mice")
   library(mice)
   install.packages("tidyverse")
   library(tidyverse)
   install.packages("cowplot")
   library(cowplot)
   install.packages("lsmeans")
   library(lsmeans)
   remotes::install_github("dustinfife/fifer")

but I get the error:
   * installing *source* package ‘fifer’ ...
   ** using staged installation
   ** R
   ** data
   ** byte-compile and prepare package for lazy loading
   Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
     there is no package called ‘flexplot’
   Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
   Execution halted
   ERROR: lazy loading failed for package ‘fifer’
   * removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/fifer’
   Error: Failed to install 'fifer' from GitHub:
     (converted from warning) installation of package ‘/var/folders/bb/yhc6r_s97ll916m079zcyn0h0000gn/T//Rtmpf6PbHc/file17105aebfec9/fifer_1.1.tar.gz’ had non-zero exit status

Can you advise me how to proceed?
Thank you

**Comment by dustinfife** [comment]
Flexplot is available on github, not cran. So you have to first:

`remotes::install_github("dustinfife/fifer")`

then 

`remotes::install_github("dustinfife/flexplot")`
