### ISSUE TITLE
Trouble Downloading

### ISSUE THREAD

**Issue by hrshin15** [dustinfife/fifer#8]
Hello, 
I am having trouble downloading the fifer package. 

install.packages("remotes")
require("remotes")
remotes::install_github("dustinfife/fifer")

Installing packages into ‘C:/Users/RShin/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Error: Failed to install 'fifer' from GitHub:
  (converted from warning) package ‘flexplot’ is not available (for R version 3.6.1)

******I am a beginner, but i believe all other packages were installed but flex plot.** I also attempted this input:**** 

install.packages("remotes")
remotes::install_github("dustinfife/flexplot")

Installing 6 packages: dplyr, rlang, tidyselect, farver, vctrs, stringi
Installing packages into ‘C:/Users/RShin/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is
  later:
        binary source needs_compilation
stringi  1.4.4  1.4.5              TRUE

  Binaries will be installed
Error: Failed to install 'flexplot' from GitHub:

thank you.

**Comment by dustinfife** [comment]
Did you cut off the text? Was there something after "Error: Failed to install 'flexplot' from GitHub:" ??

**Comment by dgreis** [comment]
I'm getting an error even after I make it through the flexplot install without an error...

```
remotes::install_github("dustinfife/fifer")
Downloading GitHub repo dustinfife/fifer@master
✓  checking for file ‘/private/var/folders/fm/mlv85l311hx38mtn6sq_vj900000gn/T/Rtmpj4BVzX/remotes173644f222669/dustinfife-fifer-bf09439/DESCRIPTION’ ...
─  preparing ‘fifer’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘fifer_1.1.tar.gz’ (432ms)
   
* installing *source* package ‘fifer’ ...
** using staged installation
** R
** data
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘lme4’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘fifer’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/fifer’
Error: Failed to install 'fifer' from GitHub:
  (converted from warning) installation of package ‘/var/folders/fm/mlv85l311hx38mtn6sq_vj900000gn/T//Rtmpj4BVzX/file173644b07e015/fifer_1.1.tar.gz’ had non-zero exit status
```

**Comment by dustinfife** [comment]
If it ever says "there is not package called xxxx," you'll need to install that package. So, try this:

```
install.packages("lme4")
devtools::install_github("dustinfife/fifer")
```

**Comment by dgreis** [comment]
Thank you!
